---
abstract: 'A searchable store backed by Lucy'
author:
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
build_requires:
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Store-Lucy
provides:
  Catmandu::Store::Lucy:
    file: lib/Catmandu/Store/Lucy.pm
    version: 0.01
  Catmandu::Store::Lucy::Bag:
    file: lib/Catmandu/Store/Lucy/Bag.pm
    version: 0
requires:
  Catmandu: 0.03
  Lucy: 0.003
  Moo: 1.00
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
